version: 2

job_defaults: &job_defaults
  docker:
    - image: circleci/node:12.9.1
  working_directory: ~/project/repo

cache_key: &cache_key angular-testing-library-deps-cache-{{ checksum "yarn.lock" }}

jobs:
  install:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: install-dependencies
          command: yarn --frozen-lockfile --non-interactive
      - save_cache:
          key: *cache_key
          paths:
            - node_modules

  lint:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: lint
          command: yarn affected:lint

  build:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: build
          command: yarn build --skip-nx-cache
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: dist
          paths:
            - .

  test:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: test
          command: yarn affected:test --ci --code-coverage

  release:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - attach_workspace:
          at: dist
      - run:
          name: release
          command: yarn semantic-release || true

  release-beta:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - attach_workspace:
          at: dist
      - run:
          name: release
          command: yarn semantic-release || true

workflows:
  version: 2
  build-test-release:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - lint
      - test:
          requires:
            - build
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - release-beta:
          requires:
            - test
          filters:
            branches:
              only:
                - beta
