version: 2

job_defaults: &job_defaults
  docker:
    - image: circleci/node:12.9.1
  working_directory: ~/project/repo

cache_key: &cache_key angular-testing-library-deps-cache-{{ checksum "yarn.lock" }}
dist_key: &dist_key angular-testing-library-dist-{{ .Revision }}

jobs:
  install:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: install-dependencies
          command: yarn --frozen-lockfile
      - save_cache:
          key: *cache_key
          paths:
            - node_modules

  lint:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: lint
          command: yarn lint

  test-lib:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: test
          command: yarn test

  build-lib:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: test
          command: yarn build
      - save_cache:
          key: *dist_key
          paths:
            - dist

  test-app:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - restore_cache:
          key: *dist_key
      - run:
          name: test
          command: yarn test:app

  release:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - restore_cache:
          key: *dist_key
      - run:
          name: release
          command: yarn semantic-release || true

workflows:
  version: 2
  build-test-release:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test-lib:
          requires:
            - install
      - build-lib:
          requires:
            - lint
            - test-lib
      - test-app:
          requires:
            - build-lib
      - release:
          requires:
            - test-app
          filters:
            branches:
              only: master
