name: ci

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build_test_release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [12, 14, 16]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: use Node.js ${{ matrix.node }} on ${{ matrix.os }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm install
      - name: build
        run: npm run build -- --skip-nx-cache
      - name: test
        run: npm run test -- --ci --code-coverage
      - name: Release
        if: github.repository == 'testing-library/angular-testing-library' && github.ref == 'refs/heads/main' && matrix.node-version == 16 && matrix.os == 'ubuntu-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
